package com.VincenzoDePascale.schedePG.list;

public enum Allineamenti {
	LEGALE_BUONO,
	LEGALE_NEUTRALE,
	LEGALE_MALVAGIO,
	NEUTRALE_BUONO,
	NEUTRALE,
	NEUTRALE_MALVAGIO,
	CAOTICO_BUONO,
	CAOTICO_NEUTRALE,
	CAOTICO_MALVAGIO
}
