package com.VincenzoDePascale.schedePG.list;

public enum Linguaggi {
	
	COMUNE, ELFICO, GIGANTE, GNOMESCO, GOBLIN, HALFLING, NANICO, ORCHESCO,
	ABISSALE,CELESTIALE, DRACONICO, GERGO_DELLE_PROFONDITA, INFERNALE, PRIMORDIALE, SILVANO, SOTTOCOMUNE

}
