package com.VincenzoDePascale.schedePG.list;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Privilegi {
	
	//barbaro
	DIFESA_SENZA_ARMATURA(Classi.BARBARO, 1, "difesa senza armatura", "Finché un barbaro non indossa alcuna armatura, la sua Classe Armatura è pari a 10 + il suo modificatore di Destrezza + il suo modificatore di Costituzione. Un barbaro può usare uno scudo e ottenere comunque questo beneficio."),
	IRA(Classi.BARBARO, 1, "ira", "In battaglia, un barbaro combatte animato da ferocia primordiale. Nel suo turno, può entrare in ira con un’azione bonus.\r\n"
			+ "Finché è in ira, ottiene i seguenti benefici, se non indossa un'armatura pesante:\r\n"
			+ "\r\n"
			+ "Dispone di vantaggio alle prove di Forza e ai Tiri Salvezza su Forza.\r\n"
			+ "Quando effettua un attacco con arma da mischia usando Forza, ottiene un bonus al tiro per i danni che aumenta man mano che egli ottiene nuovi livelli da barbaro, come indicato nella colonna \"Danni dell'Ira\" nella tabella \"Barbaro\".\r\n"
			+ "Un barbaro dispone di resistenza ai danni contundenti, perforanti e taglienti.\r\n"
			+ "Se un barbaro è in grado di lanciare incantesimi, non può lanciarli o concentrarsi su di essi quando è in ira.\r\n"
			+ "L'Ira del barbaro dura 1 minuto. Termina anticipatamente se cade Privo di Sensi o se il suo turno termina e non ha attaccato alcuna creatura ostile dal suo ultimo turno o non ha subito danni da allora. Un barbaro può anche porre fine alla sua ira nel proprio turno, come un’azione bonus.\r\n"
			+ "Una volta entrato in ira per il numero di volte indicato dal suo livello di barbaro nella colonna \"Ira\" nella tabella \"Barbaro\", un barbaro deve completare un riposo lungo prima di poter entrare di nuovo in ira."),
	ATTACCO_IRRUENTO(Classi.BARBARO, 2, "attacco irruento", "A partire dal 2° livello, un barbaro può ignorare ogni preoccupazione per la sua difesa e attaccare in preda a una feroce disperazione. Quando effettua il suo primo attacco nel suo turno, può decidere di sferrare un attacco irruento. Così facondo dispone di vantaggio ai tiri per colpire in mischia che usano Forza durante questo turno, ma i tiri per colpire contro di lui dispongono di vantaggio fino a suo turno successivo."),
	PERCEZIONE_DEL_PERICOLO(Classi.BARBARO, 2, "percezione del pericolo", "Dal 2° livello, un barbaro ottiene un percezione prodigiosa di tutto ciò che nei paraggi non è come dovrebbe essere cosa che agevola quando deve schivare i pericoli. Un barbaro dispone di vantaggio ai Tiri Salvezza su Destrezza contro effetti che può vedere, come trappole e incantesimi. Per ottenere questo beneficio, non deve essere accecato, assordato o Incapacitato."),
	CAMMINO_PRIMORDIALE_liv3(Classi.BARBARO, 3, "cammino primordiale", "Al 3° livello, un barbaro sceglie un Cammino Primordiale che definisce la natura della sua furia. Questa scelta ti conferisce alcuni privilegi al 3° livello, e poi di nuovo al 6°, 10° e 14° livello."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_BARBARO(Classi.BARBARO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un barbaro può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	ATTACCO_EXTRA_BARBARO(Classi.BARBARO, 5, "attacco extra", "A partire dal 5° livello, un barbaro può attaccare due volte anziché una, ogni volta che effettua l'azione di Attacco nel proprio turno."),
	MOVIMENTO_VELOCE(Classi.BARBARO, 5, "movimento veloce", "A partire dal 5° livello, la velocità del barbaro aumenta di 3 metri purché il barbaro non indossi un'armatura pesante."),
//	PRIVILEGIO_DEL_CAMMINO("privilegio del cammino", ""),
	ISTINTO_FERINO(Classi.BARBARO, 7, "istinto ferino", "Al 7° livello, gli istinti del barbaro sono talmente affinati da fornirgli vantaggio ai tiri per l'iniziativa.\r\n"
			+ "Inoltre, se il barbaro è sorpreso all'inizio del combattimento e non è incapacitato, può agire normalmente nel suo primo turno, ma solo se entra in ira prima di fare qualsiasi altra cosa in quel turno."),
	CRITICO_BRUTALE(Classi.BARBARO, 9, "critico brutale", "A partire dal 9° livello, un barbaro può tirare un dado dell'arma aggiuntivo quando determina i danni extra di un colpo critico con un attacco in mischia.\r\n"
			+ "Questo effetto aumenta a due dadi aggiuntivi al 13° livello e a tre dadi aggiuntivi al 17° livello."),
	IRA_IMPLACABILE(Classi.BARBARO, 11, "ira implacabile", "A partire dall'11° livello, grazie alla sua ira il barbaro può continuare a combattere nonostante le ferite più gravi. Se scende a 0 punti ferita mentre è in ira e non è ucciso sul colpo, può effettuare un Tiro Salvezza su Costituzione con CD 10. Se lo supera, rimane invece a 1 punto ferita.\r\n"
			+ "Ogni volta che utilizza questo privilegio dopo la prima, la CD aumenta di 5. Quando completa un riposo breve o lungo la CD è ripristinata a 10."),
	IRA_PERSISTENTE(Classi.BARBARO, 15, "ira persistente", "A partire dal 15° livello, l'ira del barbaro è talmente feroce che termina prematuramente solo se il barbaro cade privo di sensi o se decide di porvi termine."),
	POTENZA_INDOMABILE(Classi.BARBARO, 18, "potenza indomabile", "A partire dal 18° livello, se il totale di una prova di Forza del barbaro è inferiore al suo punteggio di Forza, il barbaro può usare il suo punteggio di Forza al posto del totale."),
	CAMMINO_PRIMORDIALE_liv20(Classi.BARBARO, 20, "cammino primordiale", "Al 20° livello, il barbaro diventa un'incarnazione del potere delle terre selvagge. I suoi punteggi di Forza e Costituzione aumentano di 4. Il suo massimo per quei punteggi diventa 24."),
	
	//bardo
	INCANTESIMI_BARDO(Classi.BARDO, 1, "incantesimi", "Un bardo ha imparato a districare e rimodellare la trama della realtà in armonia con i suoi desideri tramite la musica. I suoi incantesimi fanno parte del suo vasto repertorio come magie che il bardo può mettere in sintonia con le situazioni più disparate. [continua]"),
	ISPIRAZIONE_BARDICA(Classi.BARDO, 1, "ispirazione bardica", "Un bardo può ispirare gli altri tramite il lirismo delle sue parole o della sua musica. Per farlo usa un'azione bonus nel suo turno per scegliere una creatura diversa da sé stesso, situata entro 18 metri da lui e in grado di sentirlo. Quella creatura ottiene un dado di Ispirazione Bardica, un d6. Per una volta entro i 10 minuti successivi, quella creatura può tirare il dado e aggiungere il risultato ottenuto a una prova di caratteristica, un tiro per colpire o un tiro salvezza da essa effettuato. La creatura può aspettare di avere tirato il d20 prima di decidere se utilizzare il dado di Ispirazione Bardica, ma deve decidere se utilizzarlo o meno prima che il DM dichiari se il tiro abbia avuto successo o meno. Una volta tirato il dado di Ispirazione Bardica, quel dado è perduto. Una creatura può possedere un solo dado di Ispirazione Bardica alla volta. Il bardo può utilizzare questo privilegio un numero di volte pari al suo modificatore di Carisma (fino a un minimo di una volta). Recupera tutti gli utilizzi spesi quando completa un riposo lungo. Il dado di Ispirazione Bardica cambia quando il bardo raggiunge livelli superiori. Il dado diventa un d8 al 5° livello, un d10 al 10° livello e un d12 al 15° livello."),
	FACTOTUM(Classi.BARDO, 2, "factotum", "A partire dal 2° livello, un bardo può aggiungere metà del suo bonus di competenza, arrotondato per difetto, a ogni prova di caratteristica da lui effettuata che non includa già il suo bonus di competenza."),
	CANTO_DI_RIPOSO(Classi.BARDO, 2, "canto di riposo", "Dal 2° livello, un bardo può usare una musica o un'orazione lenitiva per infondere nuova vita nei suoi alleati durante un riposo breve. Se il bardo o le eventuali creature amiche in grado di udire la sua esibizione recuperano punti ferita alla fine di un riposo breve spendendo uno o più Dadi Vita, ognuna di quelle creature recupera 1d6 punti ferita extra. I punti ferita extra aumentano quando il bardo raggiunge livelli superiori: 1d8 al 9° livello, 1d10 al 13° livello e 1d12 al 17° livello."),
	COLLEGIO_BARDICO(Classi.BARDO, 3, "collegio bardico", "Al 3° livello, un bardo apprende le tecniche più avanzate di un collegio bardico a sua scelta come ad esempio il Collegio della Sapienza. Il collegio a sua scelta gli conferisce alcuni privilegi al 3° livello e poi di nuovo al 6° e al 14° livello."),
	MAESTRIA_BARDO(Classi.BARDO, 3, "maestria", "Al 3° livello, un bardo sceglie due tra le sue competenze nelle abilità. Il suo bonus di competenza raddoppia in ogni prova di caratteristica effettuata usando una delle competenza scelte. Al 10° livello, un bardo può scegliere altre due competenze nelle abilità per ottenere questo beneficio."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_BARDO(Classi.BARDO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un bardo può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	FONTE_DI_ISPIRAZIONE(Classi.BARDO, 5, "fonte di ispirazione", "A partire dal 5° livello, un bardo recupera tutti i suoi utilizzi spesi di Ispirazione Bardica quando completa un riposo breve o lungo."),
	CONTROFASCINO(Classi.BARDO, 6, "controfascino", "Al 6° livello, un bardo ottiene la capacità di usare note musicali o parole del potere per interferire negli effetti di influenza mentale. Con un'azione può iniziare un'esibizione che dura fino alla fine del suo turno successivo. Durante quel periodo, il bardo e ogni creatura amica entro 9 metri da lui dispongono di vantaggio ai tiri salvezza per non essere affascinati o spaventati. Una creatura deve essere in grado di sentire il bardo per ottenere questo beneficio. L'esibizione termina prematuramente se il bardo diventa incapacitato o è ridotto al silenzio, o se vi pone fine volontariamente (non è richiesta un'azione per farlo)."),
//	PRIVILEGIO_DEL_COLLEGIO_BARDICO("privilegio del collegio bardico", ""),
	SEGRETI_MAGICI(Classi.BARDO, 10, "segreti magici", "Giunto al 10° livello, un bardo ha attinto alle conoscenze magiche provenienti da una vasta gamma di discipline. Il bardo sceglie due incantesimi di qualsiasi classe, inclusa questa stessa classe. Ogni incantesimo scelto deve essere di un livello che il bardo sia in grado di lanciare, come indicato nella tabella, oppure deve essere un trucchetto. Gli incantesimi scelti contano come incantesimi da bardo e vanno inclusi nel numero specificato dalla colonna \"Incantesimi Conosciuti\" nella tabella. Un bardo apprende due incantesimi aggiuntivi di qualsiasi classe al 14° livello e poi di nuovo al 18° livello."),
	ISPIRAZIONE_SUPERIORE(Classi.BARDO, 20, "ispirazione superiore", "Al 20° livello, quando il bardo tira per l'iniziativa e non gli rimane alcun utilizzo di Ispirazione Bardica, ne recupera un utilizzo."),
	
	//chierico
	INCANTESIMI_CHIERICO(Classi.CHIERICO, 1, "incantesimi", "Un chierico è un tramite del potere divino, e come tale è in grado di lanciare incantesimi da chierico. [continua]"),
	DOMINIO_DIVINO(Classi.CHIERICO, 1, "dominio divino", "Il chierico sceglie un dominio correlato alla sua divinità:\r\n"
			+ "\r\n"
			+ "Conoscenza, Guerra, Inganno, Luce, Natura, Tempesta o Vita. Ogni dominio è descritto in dettagliato alla fine della sezione di questa classe e fornisce esempi di varie divinità a esso associate. Questa scelta conferisce al chierico alcuni incantesimi di dominio e altri privilegi al 1° livello. Conferisce inoltre ulteriori modi di utilizzare incanalare Divinità quando il chierico ottiene quel privilegio al 2° livello e ulteriori benefici al 6°, 8° e 17° livello.\r\n"
			+ "\r\n"
			+ "Incantesimi di dominio\r\n"
			+ "A ogni dominio corrisponde una lista di incantesimi (gli incantesimi di dominio) che il chierico ottiene ai livelli da chierico indicati nella descrizione del dominio. Quando il chierico ottiene un incantesimo di dominio, quell'incantesimo è sempre considerato preparato e non conta al fine di determinare il numero di incantesimi che il chierico può preparare ogni giorno. Se il chierico possiede un incantesimo di dominio che non compare sulla lista degli incantesimi da chierico, quell'incantesimo è comunque considerato un incantesimo da chierico per lui."),
	INCANALARE_DIVINITA(Classi.CHIERICO, 2, "incanalare divinità", "Al 2° livello, un chierico ottiene la capacità di incanalare energia divina direttamente dalla sua divinità e usa quell'energia per alimentare gli effetti magici. Un chierico parte con due effetti di questo tipo: Scacciare Non Morti e un effetto determinato dal suo dominio. Alcuni domini conferiscono al chierico degli effetti aggiuntivi man mano che avanza di livello, come indicato nella descrizione del dominio. Quando un chierico utilizza Incanalare Divinità, può scegliere quale effetto creare. Deve poi completare un breve o lungo riposo per utilizzare di nuovo Incanalare Divinità. Alcuni effetti di Incanalare Divinità richiedono dei tiri salvezza. Quando un chierico utilizza un tale effetto, la CD è pari alla CD del tiro salvezza dei suoi incantesimi da chierico. A partire dal 6° livello, un chierico può utilizzare Incanalare Divinità due volte tra un riposo e l'altro, e a partire dal 18° livello, può utilizzarlo tre volte tra un riposo e l'altro. Quando completa un breve o lungo riposo, recupera gli ​​utilizzi spesi.\r\n"
			+ "\r\n"
			+ "Incanalare Divinità: scacciare non morto\r\n"
			+ "Con un'azione, il chierico brandisce il suo simbolo sacro e pronuncia una preghiera di condanna nei confronti dei non morti. Ogni non morto che è in grado di vedere o sentire il chierico e si trova entro 9 metri da lui deve effettuare un tiro salvezza su Saggezza. Se lo fallisce, la creatura è scacciata per 1 minuto o finché non subisce danni. Una creatura scacciata deve spendere i suoi turni tentando di allontanarsi il ​​più lontano possibile dal chierico e non può volontariamente muoversi in uno spazio entro 9 metri dal chierico. Inoltre, non può effettuare reazioni. Come sua azione, può usare solo l'azione di scatto o tentare di fuggire da un effetto che gli impedisce di muoversi. Se non può muoversi in alcun luogo, la creatura può usare l'azione di Schivata."),
//	PRIVILEGIO_DEL_DOMINIO_DIVINO("privilegio del dominio divino", ""),
	AUMENTO_PUNTEGGI_CARATTERISTICA_CHIERICO(Classi.CHIERICO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un chierico può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	DISTRUGGERE_NON_MORTI(Classi.CHIERICO, 5, "distruggere non morti", "A partire dal 5° livello, quando un non morto fallisce il suo tiro salvezza contro il privilegio Scacciare Non Morti del chierico, quella creatura viene immediatamente distrutta se il suo grado di sfida è pari o inferiore a una certa soglia, come indicato dalla tabella \"Distruggere Non Morti\"."),
	INTERVENTO_DIVINO(Classi.CHIERICO, 10, "intervento divino", "A partire dal 10° livello, un chierico può appellarsi alla propria divinità affinché intervenga a suo beneficio nel momento del bisogno. Per implorare l'aiuto della sua divinità, il chierico deve usare un'azione. Deve descrivere l'assistenza che desidera ottenere e tirare un dado percentuale. Se ottiene con il tiro un numero pari o inferiore al suo livello da chierico, la divinità interviene. È Il DM a scegliere la natura dell'intervento; l'effetto di qualsiasi incantesimo da chierico o incantesimo da dominio clericale è appropriato. Se la divinità interviene, il chierico non può più utilizzare questo privilegio per 7 giorni. Altrimenti può utilizzarlo di nuovo dopo aver completato un lungo riposo. Al 20° livello, la richiesta di intervento del chierico ha successo automaticamente, senza che sia richiesto alcun tiro."),
	
	//druido
	DRUIDICO(Classi.DRUIDO, 1, "druidico", "Un druido conosce il Druidico, il linguaggio segreto del suo ordine: può parlare in quel linguaggio e usarlo per lasciare messaggi segreti. Il druido e coloro che conoscono questo linguaggio sono in grado di avvistare questi messaggi automaticamente. Altri possono notare la presenza di un messaggio in Druidico superando la prova Saggezza (Percezione) con CD 15, ma non possono decifrarlo senza l'aiuto della magia."),
	INCANTESIMI_DRUIDO(Classi.DRUIDO, 1, "incantesimi", "Un druido attinge all'essenza divina della natura stessa e può lanciare incantesimi che modellano tale essenza in base alla sua volontà. [continua]"),
	FORMA_SELVATICA(Classi.DRUIDO, 2, "forma selvatica", "A partire dal 2° livello, un druido può usare la sua azione per assumere magicamente la forma di una bestia che ha già visto in precedenza. Può utilizzare questo privilegio due volte e recupera gli utilizzi spesi quando completa un riposo breve o lungo. Il livello da druido determina le bestie in cui egli può trasformarsi, come indicalo nella tabella \"Forme Bestiali\". Al 2° livello, per esempio, può trasformarsi in qualsiasi bestia che abbia un grado di sfida pari o inferiore a 1/4 che non abbia una velocità di nuotare o di volare. Un druido può rimanere in forma bestiale per un numero di ore pari alla metà del suo livello da druido (arrotondato per difetto), poi torna alla sua forma normale, a meno che non spenda un altro utilizzo di questo privilegio. Può tornare alla sua forma normale anticipatamente usando un'azione bonus nel suo turno. Torna automaticamente alla sua forma normale se cade privo di sensi, scende a 0 punti ferita o muore. [continua]"),
	CIRCOLO_DRUIDICO(Classi.DRUIDO, 2, "circolo druidico", "Al 2° livello, un druido sceglie di aderire a un circolo druidico, come quello della Terra. Questa scelta gli conferisce alcuni privilegi al 2° livello e poi di nuovo al 6°, 10° e 14° livello."),
//	PRIVILEGIO_DEL_CIRCOLO_DRUIDICO("privilegio del circolo druidico", ""),
	AUMENTO_PUNTEGGI_CARATTERISTICA_DRUIDO(Classi.DRUIDO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un druido può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	CORPO_SENZA_TEMPO_DRUIDO(Classi.DRUIDO, 18, "corpo senza tempo", "A partire dal 18° livello, la magia primordiale che fluisce nel druido rallenta il suo invecchiamento. Per ogni 10 anni trascorsi, il corpo del druido invecchia soltanto di 1 anno."),
	INCANTESIMI_BESTIALI(Classi.DRUIDO, 18, "incantesimi bestiali", "A partire dal 18° livello, un druido può lanciare molti dei suoi incantesimi da druido in qualsiasi forma assunta utilizzando Forma Selvatica. Può fornire le componenti somatiche e verbali di un incantesimo da druido anche quando è in forma bestiale, ma non è in grado di fornire componenti materiali."),
	ARCIDRUIDICO(Classi.DRUIDO, 20, "arcidruidico", "Al 20° livello, un druido può utilizzare Forma Selvatica un numero illimitato di volte. Può inoltre ignorare le componenti verbali e somatiche dei suoi incantesimi da druido, nonché le eventuali componenti materiali prive di un costo e quelle che non sono consumate da un incantesimo. Un druido ottiene questo beneficio sia nella sua forma normale che nella forma bestiale assunta grazie a Forma Selvatica."),
	
	//guerriero
	RECUPERO_ENERGIA(Classi.GUERRIERO, 1, "recupero energia", "Hai una fonte limitata di energia a cui puoi attingere per rimetterti dalle ferite. Durante il tuo turno, puoi usare un’azione bonus per recuperare punti ferita pari a 1d10 + il tuo livello da guerriero. Una volta impiegato questo privilegio, devi terminare un riposo breve o lungo prima di riutilizzarlo."),
	STILE_DI_COMBATTIMENTO_GUERRIERO(Classi.GUERRIERO, 1, "stile di combattimento", "Come tua specializzazione adotti un particolare stile di combattimento. Scegli una delle seguenti opzioni. Non puoi acquisire più di una volta lo stesso Stile di Combattimento, anche se in seguito ottieni una nuova scelta."),
	AZIONE_IMPETUOSA(Classi.GUERRIERO, 2, "azione impetuosa", "A partire dal 2° livello, puoi spingerti oltre i tuoi normali limiti per brevi periodi di tempo. Durante il tuo turno, puoi eseguire un’azione aggiuntiva oltre alla tua normale azione e una possibile azione bonus.\r\n"
			+ "\r\n"
			+ "Una volta impiegato questo privilegio, devi terminare un riposo breve o lungo prima di riutilizzarlo. A partire dal 17° livello, puoi utilizzarlo due volte prima di riposare, ma solo una volta durante lo stesso turno."),
	ARCHETIPO_MARZIALE(Classi.GUERRIERO, 3, "archetipo marziale", "Al 3° livello, puoi scegliere un archetipo da emulare con il tuo stile e le tue tecniche di combattimento, come quello del Campione. Il tuo archetipo ti conferisce privilegi al 3° livello e ancora al 7°, 10°, 15° e 18° livello."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_GUERRIERO(Classi.GUERRIERO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un guerriero può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	ATTACCO_EXTRA_GUERRIERO(Classi.GUERRIERO, 5, "attacco extra", "A partire dal 5° livello, puoi attaccare due volte, invece che una volta, ogni volta che effettui l’azione Attaccare durante il tuo turno.\r\n"
			+ "\r\n"
			+ "Il numero di attacchi incrementa a tre quando raggiungi l’11° livello in questa classe e a quattro quando raggiungi il 20° livello in questa classe."),
//	PRIVILEGIO_ARCHETIPO_MARZIALE("privilegio archetipo marziale", ""),
	INDOMITO(Classi.GUERRIERO, 9, "indomito", "A partire dal 9° livello, puoi ritirare un tiro salvezza che hai fallito. Se lo fai, devi usare il nuovo tiro, e non puoi più usare questo privilegio fino a quando non terminerai un riposo lungo.\r\n"
			+ "\r\n"
			+ "Puoi usare questo privilegio due volte tra ogni riposo lungo a partire dal 13° livello e tre volte tra ogni riposo lungo a partire dal 17° livello."),
	
	//ladro
	ATTACCO_FURTIVO(Classi.LADRO, 1, "attacco furtivo", "A partire dal 1° livello, impari a colpire con precisione e sfruttare le distrazioni dell’avversario. Una volta per turno, puoi infliggere 1d6 danni extra a una creatura che colpisci con un attacco se godi di vantaggio sul tiro per colpire. L’attacco deve impiegare un’arma di precisione o a distanza.\r\n"
			+ "\r\n"
			+ "Non hai bisogno di vantaggio sul tiro per colpire se un altro nemico del bersaglio si trova entro 1,5 metri da esso, quel nemico non è inabile, e non hai svantaggio sul tiro per colpire.\r\n"
			+ "\r\n"
			+ "L’ammontare di danno aggiuntivo aumenta con i tuoi livelli in questa classe come indicato nella colonna Attacco Furtivo della tabella Il Ladro."),
	GERGO_LADRESCO(Classi.LADRO, 1, "gergo ladresco", "Durante il tuo addestramento da ladro hai appreso il gergo dei ladri, una miscela segreta di dialetti, gergo e codici che ti permettono di nascondere dei messaggi in conversazioni apparentemente normali. Solo un’altra creatura che conosca il gergo dei ladri può comprendere questi messaggi. Ci vuole il quadruplo del tempo per trasmettere un simile messaggio rispetto alla normale conversazione.\r\n"
			+ "\r\n"
			+ "Inoltre, comprendi una serie di segni e simboli segreti impiegati per inviare messaggi semplici e brevi, per identificare un’area come pericolosa o territorio della gilda dei ladri, se c’è del bottino nelle vicinanze, o se le persone del luogo sono facili prede o possano fornire un rifugio ad un ladro in fuga."),
	MAESTRIA_LADRO(Classi.LADRO, 1, "maestria", "Al 1° livello, scegli due tue competenze nelle abilità, o una delle tue competenze nelle abilità e la tua competenza con gli attrezzi da scasso. Il tuo bonus di competenza è raddoppiato per qualsiasi prova di caratteristica che usi una delle competenze scelte.\r\n"
			+ "\r\n"
			+ "Al 6° livello, puoi scegliere altre due competenze (in abilità o attrezzi da scasso) su cui applicare questo beneficio."),
	AZIONE_SCALTRA(Classi.LADRO, 2, "azione scaltra", "A partire dal 2° livello, pensiero rapido e grande coordinazione ti permettono di muoverti e agire velocemente. Puoi effettuare un’azione bonus durante ciascun tuo turno in combattimento. Quest’azione può essere usata solo per effettuare le azioni Disimpegnarsi, Nascondersi o Scattare."),
	ARCHETIPO_LADRESCO(Classi.LADRO, 3, "archetipo ladresco", "Al 3° livello, puoi scegliere un archetipo da emulare nell’esercizio delle tue capacità ladresche, come quello del furfante. Il tuo archetipo conferisce privilegi al 3° livello e ancora al 9°, 13° e 17° livello."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_LADRO(Classi.LADRO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un ladro può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	SCHIVATA_PRODIGIOSA(Classi.LADRO, 5, "schivata prodigiosa", "A partire dal 5° livello, quando un attaccante che sei in grado di vedere ti colpisce con un attacco, puoi usare la tua reazione per dimezzare il danno dell’attacco effettuato contro di te."),
	ELUSIONE(Classi.LADRO, 7, "elusione", "A partire dal 7° livello, puoi tirarti fuori rapidamente da certe aree di effetto, come quella del soffio infuocato di un drago rosso o l’incantesimo tempesta di ghiaccio. Quando sei vittima di un effetto che ti permette di compiere un tiro salvezza su Destrezza per dimezzare i danni, non subisci danni se superi il tiro salvezza, e solo metà danni se lo fallisci."),
//	PRIVILEGIO_DI_ARCHETIPO_LADRESCO("privilegio dell'archetipo ladresco", ""),
	DOTE_AFFIDABILE(Classi.LADRO, 11, "dote attidabile", "Dall’11° livello, hai affinato le tue abilità prescelte quasi alla perfezione. Ogni volta che devi compiere una prova di caratteristica che ti permette di sommare il tuo bonus di competenza, puoi trattare il risultato di 9 o meno su un d20 come fosse 10."),
	PERCEZIONE_CIECA(Classi.LADRO, 14, "percezione cieca", "A partire dal 14° livello, se sei in grado di udirla, sei consapevole della posizione di qualsiasi creatura invisibile o nascosta entro 3 metri da te."),
	MENTE_SFUGGENTE(Classi.LADRO, 15, "mente sfuggente", "Per il 15° livello, la tua mente ha acquisito una grande forza. Ottieni la competenza nei tiri salvezza su Saggezza."),
	INAFFERRABILE(Classi.LADRO, 18, "inafferrabile", "A partire dal 18° livello, sei così evasivo che è difficile che gli avversari riescano a prenderti in fallo. Nessun tiro per colpire gode di vantaggio contro di te, a meno che tu non sia inabile."),
	COLPO_DI_FORTUNA(Classi.LADRO, 20, "colpo di fortuna", "Al 20° livello, hai una prodigiosa predisposizione per riuscire nel momento del bisogno. Se il tuo attacco manca un bersaglio che si trovi nella tua gittata, puoi trasformarlo in un attacco riuscito. In alternativa, se fallisci una prova di caratteristica, puoi trattare il risultato del d20 come se fosse 20.\r\n"
			+ "Una volta usato questo privilegio, non lo puoi riusare fino a quando non termini un riposo breve o lungo."),
	
	//mago
	INCANTESIMI_MAGO(Classi.MAGO, 1, "incantesimi", "Un mago è uno studioso di magia arcana: possiede un libro degli incantesimi in cui sono contenuti gli incantesimi che costituiscono le prime scintille del suo futuro potere. [continua]"),
	RECUPERO_ARCANO(Classi.MAGO, 1, "recupero arcano", "Un mago impara a recuperare parte della sua energia magica studiando il suo libro degli incantesimi. Una volta al giorno, quando completa un riposo breve, il mago sceglie quali slot incantesimo spesi desidera recuperare. Questi slot incantesimo possono avere un livello totale pari o inferiore alla metà del livello da mago (arrotondato per eccesso) e nessuno slot può essere di livello pari o superiore al 6°. Per esempio, un mago di 4° livello può recuperare slot incantesimo per un valore totale di due livelli. Potrà quindi recuperare uno slot di 2° livello o due slot di 1° livello."),
	TRADIZIONE_ARCANA(Classi.MAGO, 2, "tradizione arcana", "Quando un mago arriva al 2° livello, sceglie una tradizione arcana che modellerà la sua pratica della magia in base ai precetti di una delle otto scuole seguenti: Abiurazione, Ammaliamento, Divinazione, Evocazione, Illusione, Invocazione, Necromanzia, Trasmutazione, tutte descritte alla fine della sezione di questa classe. La scuola scelta conferisce al mago alcuni privilegi al 2° livello e poi di nuovo al 6°, 10° e 14° livello."),
//	PRIVILEGIO_DELLA_TRADIZIONE_ARCANA("privilegio della tradizione arcana", ""),
	AUMENTO_PUNTEGGI_CARATTERISTICA_MAGO(Classi.MAGO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un mago può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	MAESTRIA_NEGLI_INCANTESIMI(Classi.MAGO, 18, "maestria negli incantesimi", "Al 18° livello, il mago raggiunge una tale maestria nell'uso di certi incantesimi da poterli lanciare a volontà. Il personaggio sceglie un incantesimo da mago di 1° livello e un incantesimo da mago di 2° livello contenuti nel suo libro degli incantesimi. Può lanciare quegli incantesimi al loro livello più basso senza spendere uno slot incantesimo quando li ha preparati. Se desidera lanciare uno di quegli incantesimi a un livello superiore, deve spendere uno slot incantesimo come di consueto."),
	INCANTESIMI_PERSONALI(Classi.MAGO, 20, "incantesimi personali", "Quando il mago arriva al 20° livello, padroneggia due potenti incantesimi che sia in grado di lanciare con minimo sforzo. Il mago sceglie due incantesimi da mago di 3° livello contenuti nel suo libro degli incantesimi come suoi incantesimi personali. Il mago considera questi incantesimi sempre preparati, non li conta ai fini di determinare il numero di incantesimi preparati e può lanciare ognuno di quegli incantesimi una volta al 3° livello senza spendere uno slot incantesimo. Quando lo fa, non può farlo di nuovo finché non completa un riposo breve o lungo. Se desidera lanciare uno di quegli incantesimi a un livello superiore, deve spendere uno slot incantesimo come di consueto."),
	
	//monaco
	DIFESA_NON_ARMATA(Classi.MONACO, 1, "difesa non armata", "A partire dal 1 ° livello, finché un monaco non indossa alcuna armatura e non impugna uno scudo, la sua CA è pari a 10 + il suo modificatore di Destrezza + il suo modificatore di Saggezza."),
	ARTI_MARZIALI(Classi.MONACO, 1, "arti marziali", "Al 1 ° livello, grazie alla sua perizia nelle arti marziali, un monaco padroneggia uno stile di combattimento che fa uso di colpi senz'armi e armi da monaco, vale a dire spade corte e qualsiasi arma da mischia semplice che non possieda la proprietà a due mani o la proprietà pesante.\r\n"
			+ "\r\n"
			+ "Un monaco ottiene i benefici seguenti finché è senz'armi o impugna soltanto armi da monaco e finché non indossa alcuna armatura e non impugna uno scudo:\r\n"
			+ "\r\n"
			+ "• Un monaco può usare Destrezza anziché Forza per i tiri per colpire e i tiri per i danni dei suoi colpi senz'armi e delle sue armi da monaco. • Un monaco può tirare un d4 al posto dei normali danni del suo colpo senz'arma o della sua arma da monaco. Questo dado cambia man mano che il personaggio acquisisce altri livelli da monaco, come indicato nella colonna \"Arti marziali\" nella tabella \"Monaco\". • Quando un monaco usa l'azione di Attacco con un colpo senz'armi o un'arma da monaco nel suo turno, può\r\n"
			+ "\r\n"
			+ "effettuare un colpo senz'armi come azione bonus. Per esempio, se il monaco effettua l'azione di Attacco con un bastone ferrato, può anche effettuare un colpo senz'armi come azione bonus, presumendo che non abbia già effettuato un'azione bonus in quel turno.\r\n"
			+ "\r\n"
			+ "Alcuni monasteri utilizzano armi da monaco dalla forma particolare. Per esempio, un monaco potrebbe usare un randello composto da due sbarre in legno collegate da una breve catena(chiamato nunchaku) o un falcetto con una lama più corta e meno ricurva (chiamato kama). A prescindere dal nome usato per un'arma da monaco, il monaco può usare le statistiche di gioco fornite dall'arma nel capitolo 5,\"Equipaggiamento\"."),
	KI(Classi.MONACO, 2, "ki", "A partire dal 2 ° livello, il monaco è in grado di imbrigliare l'energia mistica del ki grazie al suo addestramento. Il suo accesso a questa energia è rappresentato da un certo numero di punti ki, determinato dal livello da monaco, come indicato nella colonna \"Punti Ki\" nella tabella \"monaco\". Un monaco può spendere questi punti per alimentare i vari privilegi del ki. Inizialmente il monaco conosce tre di questi privilegi: Difesa del paziente, Passo del Vento e Raffica di colpi. Apprenderà altri privilegi del ki,quel punto non è più disponibile finché il monaco non completa un riposo breve o lungo, alla fine del quale il monaco riassorbe in sé tutto il ki che aveva speso.Il monaco deve trascorrere almeno 30 minuti in meditazione durante il riposo per recuperare i suoi punti ki. Alcuni privilegi del ki di un monaco richiedono al bersaglio di effettuare un tiro salvezza per resistere ai loro effetti. [continua]"),
	MOVIMENTO_SENZA_ARMATURA(Classi.MONACO, 2, "movimento non armato", "A partire dal 2 ° livello, la velocità di un monaco aumenta di 3 metri finché il monaco non indossa alcuna armatura o non impugna uno scudo. Questo bonus aumenta man mano che il personaggio acquisisce altri livelli da monaco, come indicato nella tabella \"Monaco\". Al 9 ° livello, un monaco ottiene la capacità di muoversi lungo le superfici verticali e sulle superfici liquide durante il suo turno senza cadere durante il movimento."),
	TRADIZIONE_MONASTICA(Classi.MONACO, 3, "tradizione monastica", "Quando si raggiunge 3 ° livello, il monaco si vota a una tradizione monastica come la Via della Mano Aperta o la Via dell'Ombra. La tradizione scelta conferisce al monaco alcuni privilegi al 3 ° livello e poi di nuovo al 6 °, 11 ° e 17 ° livello."),
	DEVIARE_PROIETTILI(Classi.MONACO, 3, "deviare proiettili", "A partire dal 3 ° livello, un monaco può usare la sua reazione per deviare o afferrare un proiettile quando viene colpito dall'attacco con un'arma a distanza. Quando lo fa, il danno che subisce dall'attacco è ridotto di 1d10 + il suo modificatore di Destrezza + il suo livello da monaco. Se il monaco riduce i danni a 0, può afferrare il proiettile, se quest'ultimo è abbastanza piccolo da essere tenuto in mano e se il monaco ha almeno una mano libera. Se il monaco afferra un proiettile in questo modo, può spendere 1 punto ki per effettuare un attacco a distanza con l'arma o con la munizione che ha appena afferrato, come parte della stessa reazione. Il monaco effettua questo attacco con competenza, a prescindere dalle sue competenze nelle armi, e il proiettile è considerato un'arma da monaco ai fini di questo attacco, con una gittata normale di 6 metri e una gittata lunga di 18 metri."),
	CADUTA_LENTA(Classi.MONACO, 4, "caduta lenta", "A partire dal 4 ° livello, un monaco può usare la sua reazione quando cade per ridurre gli eventuali danni da caduta di un ammontare pari a cinque volte il suo livello da monaco."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_MONACO(Classi.MONACO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un monaco può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	ATTACCO_EXTRA_MONACO(Classi.MONACO, 5, "attacco extra", "A partire dal 5 ° livello, un monaco può attaccare due volte, anziché una, ogni volta che effettua l'azione di attacco nel proprio turno."),
	COLPO_STORDENTE(Classi.MONACO, 5, "colpo stordente", "A partire da 5 ° livello, un monaco può interferire con il ki che fluisce nel corpo di un avversario. Quando il monaco colpisce un'altra creatura con un attacco con un'arma da mischia, può spendere 1 punto ki per tentare un colpo stordente. Il bersaglio deve superare un tiro salvezza su Costituzione, altrimenti sarà stordito fino alla fine del turno successivo del monaco."),
	COLPI_KI_POTENZIATI(Classi.MONACO, 6, "colpi ki potenziati", "A partire dal 6 ° livello, i colpi senz'armi del monaco sono considerati magici ai fini di oltrepassare la resistenza e l'immunità agli attacchi e ai danni non magici."),
//	PRIVILEGIO_DELLA_TRADIZIONE_MONASTICA("privilegio della tradizione", ""),
	EVASIONE(Classi.MONACO, 7, "evasione", "Al 7 ° livello, grazie alla sua agilità istintiva, il monaco può schivare certi effetti ad area, come il soffio di fulmine di un drago blu o un incantesimo palla di fuoco. Quando il monaco è soggetto a un effetto che gli consente di effettuare un tiro salvezza su Destrezza per dimezzare i danni, non subisce alcun danno se supera il tiro salvezza, e soltanto la metà dei danni se lo fallisce."),
	MENTE_LUCIDA(Classi.MONACO, 7, "mente lucida", "A partire dal 7 ° livello, un monaco può utilizzare l'azione per porre fine a un effetto su te stesso che lo rende affascinato o spaventato."),
	PUREZZA_DEL_CORPO(Classi.MONACO, 10, "purezza del corpo", "Al 10 ° livello, il monaco ha una tale padronanza del ki da diventare immune alle malattie e ai veleni."),
	LINGUA_DEL_SOLE_E_DELLA_LUNA(Classi.MONACO, 13, "lingua del sole e della luna", "A partire dal 13 ° livello, un monaco impara a sfiorare il ki delle altre menti ed è in grado di comprendere tutti i linguaggi parlati. Inoltre, qualsiasi creatura che sia in grado di capire ciò che il monaco dice."),
	ANIMA_ADAMANTINA(Classi.MONACO, 13, "anima adamantina", "Cominciando a 14 ° livello, il monaco ha una tale padronanza del ki da ottenere competenza in tutti i tiri salvezza. Inoltre, ogni volta che effettua un tiro salvezza e fallisce, può spendere 1 punto ki per ripetere il tiro. Deve usare il nuovo risultato."),
	CORPO_SENZA_TEMPO_MONACO(Classi.MONACO, 15, "corpo senza tempo", "Al 15 ° livello, il monaco è pervaso dal ki al punto che non è toccato dalla fragilità della vecchiaia e non può invecchiare magicamente. Tuttavia, può sempre morire di vecchiaia. Inoltre, non ha più bisogno di bere o di mangiare."),
	CORPO_VUOTO(Classi.MONACO, 18, "corpo vuoto", "A partire dal 18 ° livello, il monaco può usare la sua azione per spendere 4 punti ki e diventare invisibile per 1 minuto. Durante quel periodo di tempo, ottiene anche resistenza a tutti danni, tranne ai danni da forza. Inoltre, il monaco può spendere 8 punti ki in modo da lanciare incantesimo proiezione astrale, senza avere bisogno di componenti materiali. Quando lo fa, non può portare nessun'altra creatura con sé."),
	PERFEZIONE_INTERIORE(Classi.MONACO, 20, "perfezione interiore", "Al 20° livello, quando il monaco tira per l'iniziativa e non gli rimane alcun punto ki, recupera 4 punti ki."),
	
	//paladino
	IMPOSIZIONE_DELLE_MANI(Classi.PALADINO, 1, "imposizione delle mani", "Il tuo tocco benedetto può guarire le ferite. Hai una riserva di potere curativo che si ripristina al termine di un riposo lungo. Con questa riserva, puoi curare un numero totale di punti ferita pari al tuo livello da paladino x 5.\r\n"
			+ "\r\n"
			+ "Con un’azione, puoi attingere al potere della riserva per ripristinare i punti ferita di una creatura con cui sei in contatto, fino al massimo rimanente nella tua riserva.\r\n"
			+ "\r\n"
			+ "In alternativa, puoi spendere 5 punti ferita dalla tua riserva di guarigione per curare il bersaglio di una malattia o neutralizzare un veleno che lo affligge. Puoi curare più malattie e neutralizzare più veleni con una singola Imposizione delle Mani, spedendo i punti ferita separatamente per ogni malanno.\r\n"
			+ "\r\n"
			+ "Questo privilegio non ha effetto su non morti o costrutti."),
	PERCEZIONE_DEL_DIVINO(Classi.PALADINO, 1, "percezione del divino", "La presenza di una forte malvagità viene percepita dai tuoi sensi come un odore nauseabondo, e un bene potente suona come musica celestiale nelle tue orecchie. Con un’azione puoi espandere la tua consapevolezza per individuare queste forze. Fino al termine del tuo prossimo turno, conosci la posizione di qualsiasi celestiale, immondo o non morto che si trovi entro 18 metri da te e che non sia dietro copertura totale. Riconosci il tipo (celestiale, immondo o non morto) di qualsiasi creatura di cui avverti la presenza, ma non la sua esatta identità (per esempio il vampiro Conte Strahd von Zarovich). All’interno della stesso raggio, puoi anche individuare la presenza di qualsiasi luogo o oggetto che sia stato consacrato o dissacrato, come per l’incantesimo santificare.\r\n"
			+ "\r\n"
			+ "Puoi usare questo privilegio un numero di volte pari ad 1 + il tuo modificatore di Carisma. Quando termini un riposo lungo, recuperi tutti gli usi consumati."),
	INCANTESIMI_PALADINO(Classi.PALADINO, 2, "incantesimi", "Al 2° livello, impari ad attingere alla magia divina tramite la meditazione e la preghiera per lanciare incantesimi come fa un chierico. Vedi La Magia per le regole generali sul lancio degli incantesimi. Vedi Le Liste degli Incantesimi per la lista degli incantesimi da paladino."),
	PUNIZIONE_DIVINA(Classi.PALADINO, 2, "punizione divina", "A partire dal 2° livello, quando colpisci una creatura con un attacco con arma da mischia, puoi spendere uno slot incantesimo per infliggere danno radiante al bersaglio, oltre al danno dell’arma. Il danno aggiuntivo è 2d8 per uno slot incantesimo di 1° livello, più 1d8 per ogni livellodell’incantesimo sopra al 1°, massimo 5d8. Il danno aumenta di 1d8 se il bersaglio è un non morto o un immondo."),
	STILE_DI_COMBATTIMENTO_PALADINO(Classi.PALADINO, 2, "stile di combattimento", "Al 2° livello, adotti un particolare stile di combattimento come tua specialità. Scegli una delle seguenti opzioni. Non puoi acquisire più di una volta lo stesso Stile di Combattimento, anche se in seguito ottieni una nuova scelta."),
	GIURAMENTO_SACRO(Classi.PALADINO, 3, "giuramento sacro", "Quando raggiungi il 3° livello, pronunci un giuramento che ti vincola come paladino per l’eternità. Fino a questo momento hai affrontato un periodo di preparazione, devoto al sentiero ma ancora non vincolato ad esso. Ora scegli un giuramento, come il Giuramento di Devozione.\r\n"
			+ "\r\n"
			+ "La tua scelta ti conferisce dei privilegi al 3° livello e poi al 7°, 15° e 20° livello. Questi privilegi includono gli incantesimi del giuramento e il privilegio Incanalare Divinità."),
	SALUTE_DIVINA(Classi.PALADINO, 3, "salute divina", "Dal 3° livello in poi, la magia divina che ti fluisce attraverso ti rende immune alle malattie."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_PALADINO(Classi.PALADINO, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un paladino può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	ATTACCO_EXTRA_PALADINO(Classi.PALADINO, 5, "attacco extra", "A partire dal 5° livello, puoi attaccare due volte, invece che una volta, ogni volta che effettui l’azione Attaccare durante il tuo turno."),
	AURA_DI_PROTEZIONE(Classi.PALADINO, 6, "aura di protezione", "A partire dal 6° livello, ogniqualvolta tu o una creatura amica entro 3 metri da te dovete effettuare un tiro salvezza, quella creatura ottiene un bonus al tiro salvezza pari al tuo modificatore di Carisma (con un bonus minimo +1). Per conferire questo bonus devi essere cosciente.\r\n"
			+ "\r\n"
			+ "Al 18° livello, la gittata di quest’aura aumenta a 9 metri."),
//	PRIVILEGIO_DEL_GUERRIERO_SACRO("privilegio del guerriero sacro", ""),
	AURA_DI_CORAGGIO(Classi.PALADINO, 10, "aura di coraggio", "A partire dal 10° livello, tu e le creature tue amiche entro 3 metri da te non potete essere spaventati finché sei cosciente.\r\n"
			+ "\r\n"
			+ "Al 18° livello, la gittata di quest’aura aumenta a 9 metri."),
	PUNIZIONE_DIVINA_MIGLIORATA(Classi.PALADINO, 11, "punizione divina migliorata", "Per l’11° livello, sei così infuso di giusta potenza che tutti i tuoi colpi con arma da mischia convogliano potere divino. Ogni qualvolta colpisci una creatura con un’arma da mischia, la creatura subisce 1d8 danni radianti aggiuntivi. Se usi la tua Punizione Divina assieme a un attacco, somma questo danno al danno aggiuntivo della Punizione Divina."),
	TOCCO_PURIFICATORE(Classi.PALADINO, 14, "tocco purificatore", "A partire dal 14° livello, puoi usare la tua azione per porre termine a un incantesimo su di te o una creatura consenziente che puoi toccare.\r\n"
			+ "\r\n"
			+ "Puoi usare questo privilegio un numero di volte pari al tuo modificatore di Carisma (minimo di una volta). Recuperi gli usi spesi al termine di un riposo lungo."),
	
	//ranger
	NEMICO_PRESCELTO(Classi.RANGER, 1, "nemico prescelto", "A partire dal 1° livello, hai sviluppato una significativa esperienza nello studio, seguire tracce, cacciare e anche parlare con un certo tipo di nemico.\r\n"
			+ "\r\n"
			+ "Scegli un tipo di nemico prescelto: aberrazioni, bestie, celestiali, costrutti, draghi, elementali, fatati, giganti, immondi, melme, mostruosità, non morti o vegetali. In alternativa puoi scegliere come nemico favorito due razze umanoidi (come gnoll e orchi).\r\n"
			+ "\r\n"
			+ "Hai vantaggio sulle prove di Saggezza (Sopravvivenza) per seguire le tracce dei tuoi nemici favoriti, oltre che alle prove di Intelligenza per ricordare informazioni su di loro. Quando ottieni questo privilegio, apprendi anche un linguaggio di tua scelta che venga parlato dal nemico prescelto, se questi è in grado di parlare.\r\n"
			+ "\r\n"
			+ "Scegli un ulteriore nemico prescelto, oltre che un linguaggio a esso associato, al 6° e 14° livello. Con l’aumentare di livello, le tue scelte dovrebbero riflettere i tipi di mostri che hai incontrato nel corso delle tue avventure."),
	ESPLORATORE_NATO(Classi.RANGER, 1, "esploratore nato", "Sei particolarmente familiare con un tipo di ambiente naturale e sei esperto nel viaggiare e sopravvivere in questa regione. Scegli un tipo di terreno prescelto: artico, costa, deserto, foresta, montagna, palude o pianura. Quando effettui una prova di Intelligenza o Saggezza collegata al tuo terreno prescelto, il tuo bonus di competenza viene raddoppiato se stai usando un’abilità in cui sei competente. [continua]"),
	STILE_DI_COMBATTIMENTO(Classi.RANGER, 2, "stile di combattimento", "Al 2° livello come tua specializzazione adotti un particolare stile di combattimento. Scegli una delle seguenti opzioni. Non puoi acquisire più di una volta lo stesso Stile di Combattimento, anche se in seguito ottieni una nuova scelta."),
	INCANTESIMI_RANGER(Classi.RANGER, 2, "incantesimi", "Quando raggiungi il 2° livello, hai imparato ad usare l’essenza magica della natura per lanciare incantesimi, in modo simile al druido. Vedi La Magia per le regole generali sul lancio degli incantesimi e Le Liste degli Incantesimi per una selezione di incantesimi da ranger."),
	ARCHETIPO_RANGER(Classi.RANGER, 3, "archetipo ranger", "A partire dal 3° livello, scegli un archetipo che cerchi di emulare, come il Cacciatore. Questa scelta ti conferisce un privilegio al 3° livello, e un altro al 7°, 11° e 15° livello."),
	CONSAPEVOLEZZA_PRIMORDIALE(Classi.RANGER, 3, "consapevolezza primordiale", "A partire dal 3° livello, puoi usare la tua azione e spendere uno slot incantesimo da ranger per concentrare la tua consapevolezza sulla regione circostante. Per 1 minuto per livello dello slot incantesimo speso, puoi percepire se le seguenti creature siano presenti entro 1,5 chilometri da te (o entro 10 chilometri se sei nel tuo terreno prescelto): aberrazioni, celestiali, draghi, elementali, fatati, immondi e non morti. Questo privilegio non rivela la posizione o il numero delle creature."),
	AUMENTO_PUNTEGGI_CARATTERISTICA_RANGER(Classi.RANGER, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un ranger può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
	ATTACCO_EXTRA_RANGER(Classi.RANGER, 5, "attacco extra", "A partire dal 5° livello, puoi attaccare due volte, invece che una volta, ogni volta che effettui l’azione Attaccare durante il tuo turno."),
//	PRIVILEGIO_DI_ARCHETIPO_DEL_RANGER("privielgio dell'archetipo del ranger", ""),
	ANDATURA_SUL_TERRENO(Classi.RANGER, 8, "andatura sul terreno", "A partire dall’8° livello, muoversi attraverso terreno difficile non magico non ti costa più movimento aggiuntivo. Puoi attraversare i vegetali non magici senza esserne rallentato e senza subire danni da essi, se presentano spine, spuntoni o simili pericoli.\r\n"
			+ "\r\n"
			+ "Inoltre, hai vantaggio sui tiri salvezza contro vegetali che sono stati creati o manipolati magicamente per impedire il movimento, come quelli creati dall’incantesimo intralciare."),
	NASCONDERSI_IN_PIENA_VISTA(Classi.RANGER, 10, "nascondersi in piena vista", "A partire dal 10° livello, puoi spendere 1 minuto a mimetizzarti. Devi avere accesso a fango fresco, terriccio, piante e fuliggine e altri materiali naturali con i quali creare il tuo camuffamento.\r\n"
			+ "\r\n"
			+ "Una volta mimetizzato in questo modo, puoi cercare di nasconderti appiattendoti contro una superficie solida, come un albero o un muro, che sia larga e alta almeno quanto te. Ottieni un bonus di +10 alle prove di Destrezza (Furtività) finché rimani fermo senza muoverti o effettuare azioni. Una volta che ti muovi o effettui un’azione o una reazione, ti devi mimetizzare di nuovo per ottenere questo beneficio."),
	SVANIRE(Classi.RANGER, 14, "svanire", "A partire dal 14° livello, puoi usare l’azione Nascondersi come azione bonus durante il tuo turno. Inoltre, le tue tracce non possono essere rilevate se non con mezzi magici, a meno che tu non decida di lasciare una scia."),
	SENSI_FERINI(Classi.RANGER, 18, "sensi ferini", "Al 18° livello, sviluppi dei sensi soprannaturali che ti aiutano a combattere le creature che non puoi vedere. Quando attacchi una creatura che non puoi vedere, la tua incapacità di vedere non comporta svantaggio ai tiri per colpire contro di essa.\r\n"
			+ "\r\n"
			+ "Sei anche consapevole della posizione di qualsiasi creatura invisibile entro 9 metri da te, purché la creatura non sia nascosta a te, e tu non sia accecato o assordato."),
	STERMINATORE_NEMICI(Classi.RANGER, 20, "sterminatore di nemici", "Al 20° livello, diventi un insuperabile cacciatore dei tuoi nemici. Una volta durante ciascun tuo turno, puoi sommare il tuo modificatore di Saggezza al tiro per colpire o al tiro di danno di un attacco effettuato contro uno dei tuoi nemici prescelti. Puoi scegliere di usare questo privilegio prima o dopo il tiro, ma prima che qualsiasi risultato del tiro venga applicato."),
	
	//stregone
	INCANTESIMI_STREGONE(Classi.STREGONE, 1, "incantesimi", "Un evento nel passato dello stregone o nella vita di un suo parente o antenato ha lasciato su di lui un segno indelebile, infondendogli una fonte di magia arcana. È questa fonte di magia, qualunque sia la sua origine, ad alimentare i suoi incantesimi. Vedi il capitolo 10 per le regole generali relative alla magia e il capitolo 11 per la lista degli incantesimi da stregone. [continua]"),
	ORIGINA_STREGONESCA(Classi.STREGONE, 1, "origine stregonesca", "Il giocatore sceglie un'origine stregonesca che definisca la fonte dei poteri magici innati dello stregone: Discendenza Draconica o Magia Selvaggia, entrambi descritti alla fine della sezione di questa classe. Questa scelta conferisce allo stregone alcuni privilegi al 1° livello e poi di nuovo al 6°, 14° e 18° livello."),
	FONTE_DI_MAGIA(Classi.STREGONE, 2, "fonte di magia", "Al 2° livello, uno stregone attinge a una profonda sorgente di magia interiore. Essa è rappresentata dai punti stregoneria, che gli consentono di creare una vasta gamma di effetti magici. [continua]"),
	METAMAGIA(Classi.STREGONE, 3, "metamagia", "Al 3° livello, uno stregone sviluppa la capacità di plasmare i suoi incantesimi per adattarli ai suoi bisogni e ottiene due delle seguenti opzioni di Metamagia a sua scelta. Ne ottiene un'altra al 10° livello e un'altra al 17° livello. [continua]"),
	AUMENTO_PUNTEGGI_CARATTERISTICA_STREGONE(Classi.STREGONE, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un stregone può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
//	PRIVILEGIO_DI_ORIGINE_STREGONESCA("privilegio dell'origine stregonesca", ""),
	RIPRISTINO_STREGONESCO(Classi.STREGONE, 20, "ripristino stregonesco", "Al 20° livello, uno stregone recupera 4 punti stregoneria spesi ogni volta che completa un riposo breve."),
	
	//warlock
	PATRONO_ULTRATERRENO(Classi.WARLOCK, 1, "patrono ultraterreno", "Al 1° livello, un warlock stipula un patto con un essere extraplanare a sua scelta: il Signore Fatato, l'Immondo o il Grande Antico, ognuno dei quali è descritto in dettaglio alla fine della sezione di questa classe. La scelta del patrono gli conferisce alcuni privilegi al 1° livello e poi ancora al 6°, 10° e 14° livello."),
	MAGIA_DEL_PATTO(Classi.WARLOCK, 1, "magia del patto", "Le ricerche arcane condotte dal warlock e l'energia magica che il suo patrono gli conferisce rendono il warlock particolarmente abile nell'uso degli incantesimi. Vedi il capitolo 10 per le regole generali relative alla magia e il capitolo 11 per la lista degli incantesimi da warlock. [continua]"),
	SUPPLICHE_OCCULTE(Classi.WARLOCK, 2, "suppliche occulte", "Dedicandosi allo studio delle scienze occulte, un warlock ha scoperto come usare alcune suppliche occulte, frammenti di conoscenze proibite che gli conferiscono persistenti doti magiche. Al 2° livello, il warlock ottiene due suppliche occulte a sua scelta. Le sue opzioni di invocazione sono descritte alla fine della sezione di questa classe. Quando il warlock raggiunge livelli superiori, ottiene ulteriori suppliche a sua scelta, come indicato nella colonna \"Suppliche Conosciute\" nella tabella \"Warlock\". Inoltre, quando acquisisce un nuovo livello, il warlock può scegliere una delle suppliche che conosce e sostituirla con un'altra che potrebbe imparare a quel livello."),
	DONO_DEL_PATTO(Classi.WARLOCK, 3, "dono del patto", "Al 3° livello, il patrono ultraterreno elargisce al warlock un dono per ricompensarlo dei suoi fedeli servigi. Il warlock ottiene uno dei privilegi seguenti a sua scelta. [continua]"),
	AUMENTO_PUNTEGGI_CARATTERISTICA_WARLOCK(Classi.WARLOCK, 4, "aumento punteggi caratteristica", "Quando arriva al 4° livello, e poi di nuovo all'8°,12°,16° e 19° livello, un warlock può aumentare di 2 un punteggio di caratteristica a sua scelta, oppure può aumentare di 1 due punteggi di caratteristica a sua scelta. Come di consueto, non è consentito aumentare un punteggio di caratteristica a più di 20 utilizzando questo privilegio."),
//	PRIVILEGIO_DEL_PATRONO_ULTRATERRENO("privilegio del patrono ultraterreno", ""),
	ARCANUM_MISTICO(Classi.WARLOCK, 11, "arcanum mistico", "All'11° livello, il patrono rivela al warlock un segreto magico chiamato arcanum. Il warlock sceglie un incantesimo di 6° livello dalla lista degli incantesimi da warlock come arcanum. Il warlock può lanciare il suo incantesimo arcanum senza spendere uno slot incantesimo. Deve completare un riposo lungo prima di poterlo fare di nuovo. Ai livelli successivi, il warlock ottiene altri incantesimi da warlock a sua scelta da lanciare in questo modo: un incantesimo di 7° livello al 13°livello, un incantesimo di 8° livello al 15° livello e un incantesimo di 9° livello al 17° livello. Recupera tutti gli utilizzi del suo Arcanum Mistico quando completa un riposo lungo."),
	MAESTRO_DEL_ACCULTO(Classi.WARLOCK, 20, "maestro dell'occulto", "Al 20° livello, il warlock è in grado di attingere alla sua riserva interiore di potere mistico quando invoca il suo patrono per riottenere gli slot incantesimo spesi. Il warlock può trascorrere 1 minuto invocando l'aiuto del suo patrono per riottenere tutti gli slot incantesimo concessi dal privilegio Magia del Patto che ha speso. Una volta riottenuti gli slot incantesimo tramite questo privilegio, il warlock deve completare un riposo lungo prima di poterlo fare di nuovo. [continua]");
	
	
	
	//PRIVILEGIO(classe, liv, "nome", desc);
	private Classi classe;
	private int livello;
	private String nome;
	private String descrizione;
	
	private Privilegi(Classi classe, int livello, String nome, String descrizione) {
		this.classe = classe;
		this.livello = livello;
		this.nome = nome;
		this.descrizione = descrizione;
	}

    @JsonValue
    public Map<String, Object> getEquipaggiamento() {
        Map<String, Object> result = new HashMap<>();
        result.put("classe", classe);
        result.put("livello", livello);
        result.put("nome", nome);
        result.put("descrizione", descrizione);
        return result;
    }

	public Classi getClasse() {
		return classe;
	}

	public int getLivello() {
		return livello;
	}

	public String getNome() {
		return nome;
	}

	public String getDescrizione() {
		return descrizione;
	}
	
}
