package com.VincenzoDePascale.schedePG.list;

public enum TipiEquip {
	BASE,
	FOCUS_ARCANO,
	FOCUS_DRUIDICO,
	SIMBOLO_SACRO,
	ARMATURA_LEGGERA,
	ARMATURA_MEDIA,
	ARMATURA_PESANTE,
	SCUDO,
	POZIONE,
	GIOCO,
	STRUMENTO,
	STRUMENTO_MUSICALE,
	STRUMENTO_DA_ARTIGIANO,
	ARMA_DA_MISCHIA_SEMPLICE,
	ARMA_A_DISTANZA_SEMPLICE,
	ARMA_DA_MISCHIA_DA_GUERRA,
	ARMA_A_DISTANZA_DA_GUERRA,
	BALESTRA_A_MANO,
	}
